txpipe/oura

docker/Dockerfile
docker/docker.md
docs/cli.md

Hi!, This PR prsents a way of start **oura** using Docker to take advantage from what containers have
In general 2:
* Due to the nature of the containers, It's an easy to run multiplatform  app.
*  It's a kickoff to have a Dockerfile template for the community  to create a binary by themselves and compare them to the artifacts created by github actions. 
* Only works for remotes nodes. 
* Cannot save the logs in a separate volume
* A `docker-compose.yml` where oura is deployed near to a Cardano node
* A `docker-compose.yml` where also is deployed near to a ELK where all the logs are pushed. This will require some more machine; but brings an *out of the box* Cardano stack with monitoring.
* If not wated to use a `docker-compose` stack, save log tail in a volume.

Enabled Docker for remote hosts

---

src/framework.rs
src/mapping.rs
src/sinks/terminal/format.rs
testdrive/elasticsearch/index-template.json

- add count of transactions to blocks
- add total coin output to transactions
- add input count to transactions
- add output count to transactions
- update terminal formatting output accordingly
- update example ES mappings accordingly

Add common data aggregations to events

---

src/filters/fingerpint.rs
src/framework.rs
src/mapper/cip25.rs
src/mapper/crawl.rs
src/mapper/map.rs
src/mapper/mod.rs
src/sinks/terminal/format.rs

This new parser will inspect metadata records looking for CIP-25 compliance. If found, a new event will be sent for each asset in the policy with the following structure:
```rust
pub struct CIP25AssetRecord {
pub policy: String,
pub id: String,
pub name: String,
pub version: Option<String>,
pub image: JsonValue,
pub media_type: Option<String>,
pub description: Option<JsonValue>,
pub raw_json: Option<JsonValue>,
}
```

feat: Add CIP-25 metadata parser

---

Cargo.lock
Cargo.toml
README.md
src/bin/oura/daemon.rs
src/filters/fingerpint.rs
src/framework.rs
src/sinks/mod.rs
src/sinks/terminal/format.rs
src/sinks/webhook/mod.rs
src/sinks/webhook/run.rs
src/sinks/webhook/setup.rs

feat: Introduce "Webhook" sink

---

src/bin/oura/watch.rs
src/filters/fingerpint.rs
src/framework.rs
src/mapper/crawl.rs
src/mapper/map.rs
src/mapper/prelude.rs
src/sinks/terminal/format.rs

feat: Add block / tx 'end' events

---

src/sinks/terminal/format.rs

fix(terminal): Avoid slicing utf-8 chars

---

src/bin/oura/dump.rs

naive fix when building without `logs` feature enabled
ex: `cargo build --release --features "fingerprint webhook kafkasink"`

fix: dump build without 'logs' feature

---

src/mapper/mod.rs
src/mapper/prelude.rs
src/sources/n2c/run.rs
src/sources/n2n/run.rs
src/utils/mod.rs
src/utils/time.rs

This PR fixes the mapping of slot => timestamp described in #50 and prepares the groundwork to introduce other more-robust strategies to allow multi-era timestamp calculation (for example, using state query mini-protocol on N2C scenarios)

fix: Slot to timestamp mapping matches public explorers

---

src/mapper/crawl.rs
src/mapper/map.rs
src/mapper/prelude.rs
src/utils/bech32.rs
src/utils/mod.rs

fix: Make bech32 encoding network-aware

---

src/mapper/prelude.rs

There's one left over to make the `EventWriter::standalone()` actually work for code examples. The struct must be public.
```
error[E0603]: struct `EventWriter` is private
--> examples/blockfetch.rs:19:13
|
19 |     mapper::EventWriter,
|             ^^^^^^^^^^^ private struct
|
```

fix: EventWriter::standalone() inaccessible

---

src/mapper/crawl.rs
src/mapper/map.rs
src/model.rs
src/sinks/terminal/format.rs

feat(model): include tx_hash in TransactionRecord

---

.github/workflows/release.yml

**i686** is too legacy for [cryptoxide v0.4.2](https://docs.rs/cryptoxide/0.4.2/cryptoxide/) which requires [_mm256_permute4x64_epi64](https://docs.rs/stdsimd/0.1.2/stdsimd/arch/x86_64/fn._mm256_permute4x64_epi64.html) which is supported on x86-64 and target feature avx2 only.

ci: Remove i686 release targets

---

.github/dependabot.yml

I have noticed release workflow is using outdated Docker actions when working on https://github.com/txpipe/oura/pull/128, we may as well include it in Dependabot config.

ci(dependabot): Auto-update GH Action versions

---

book/src/sources/n2c.md
book/src/sources/n2n.md

Docs: Update Mapper to include cbor

---

src/bin/oura/daemon.rs
src/sinks/assert/checks.rs
src/sinks/assert/mod.rs
src/sinks/assert/prelude.rs
src/sinks/assert/run.rs
src/sinks/assert/setup.rs
src/sinks/mod.rs

With the goal of moving towards a CD pipeline, we introduce a new `Assert` sink.
The sink works by consuming incoming events and running an expanding set of "assertions" for each one. The result of the assertions are logged. If specified via configuration, a failed assertion will panic and terminate the pipeline (useful for automation).
In this initial PR we're including the following set of assertions:
`block_depth_doesnt_skip_numbers`
`block_slot_increases`
`block_previous_hash_matches`
`event_timestamp_increases`
`tx_records_matches_block_count`
Ideally, we'll keep growing the list with more specific checks for each event. There's also room for adding checks that include well-known, expected values (aka: asserting values for particular blocks).
The end-goal is to have a comprehensive …

feat: Introduce the 'Assert' sink

---

src/mapper/prelude.rs
src/utils/mod.rs
src/utils/time.rs

In this PR, we expand on the existing "naive" time provider to support timestamp calculation for the Byron era.

feat: Implement multi-era time

---

Cargo.lock
Cargo.toml
src/bin/oura/daemon.rs
src/bin/oura/dump.rs
src/bin/oura/watch.rs
src/mapper/prelude.rs
src/sources/n2c/run.rs
src/sources/n2n/run.rs
src/utils/facade.rs
src/utils/metrics.rs
src/utils/mod.rs

This PR introduces a `/metrics` endpoint that uses Prometheus format to expose metrics about the progress of the pipeline.
Each stage (source / sink) is responsible for notifying their progress as they process each event. This notifications are then aggregated via counters & gauges and exposed via HTTP using the well-known Prometheus encoding.
This PR includes the following metrics:
- `chain_tip`: the last detected tip of the chain (height)
- `rollback_count`: number of rollback events occurred
- `source_current_slot`: last slot processed by the source of the pipeline
- `source_current_height`: last height (block #) processed by the source of the pipeline
- `source_event_count`:  number of events processed by the source of the pipeline
- `sink_current_slot`: last slot processed by the …

feat: Implement Prometheus metric exporter

---

book/src/filters/selection.md

docs: Add examples of complex selection filters

---

Cargo.lock
Cargo.toml
src/bin/oura/daemon.rs
src/sinks/aws_sqs/mod.rs
src/sinks/aws_sqs/run.rs
src/sinks/aws_sqs/setup.rs
src/sinks/mod.rs

This PR introduces a new sink that sends each event to an AWS SQS message queue.
- a new feature flag `aws` is added to enable the feature / dependencies
- It supports both FIFO and non-FIFO queues
- For FIFO queues, it uses a configurable message group id and the event fingerprint for the message id.
- It uses the default credentials provider chain logic as common AWS libraries (env vars, .aws/credentials, EC2 context, etc)
- the built-in retry logic of the library is used for failed requests. Max retries is configurable at the sink-level.
Known Limitations:
- SQS has a 256kb payload size limit. This is good enough for individual events, but it won't handle blocks when the `include_cbor_hex` option is enabled.

feat: Introduce AWS SQS Sink

---

book/src/usage/daemon.md
src/bin/oura/daemon.rs
src/utils/cursor.rs

feat: CLI option to override configured cursor in daemon mode

---

src/bin/oura/dump.rs
src/bin/oura/watch.rs
src/sources/common.rs
src/sources/n2c/setup.rs
src/sources/n2n/setup.rs
src/utils/mod.rs
src/utils/retry.rs

Networks errors or node restarts are common scenarios in long-running operations. Under certain circumstances, the Cardano node might take a while before exposing the corresponding sockets for inbound connections. Upon initialization, if Oura isn't able to connect to the specified Cardano node, it will exit immediately with the corresponding error message.
This PR implements a configurable retry logic that will execute several connection attempts to avoid exiting prematurely if the Cardano node is still initializing. There's a delay between each attempt to avoid stressing the network stack. This delay increases exponentially up to a configurable max value.
Example configuration:
```toml
[source.retry_policy]
connection_max_retries = 3
connection_max_backoff = 20 # in seconds
```
closes …

feat: Add connection-retry logic with exponential backoff

---

src/mapper/byron.rs
src/mapper/map.rs
src/model.rs
src/utils/mod.rs
src/utils/time.rs

feat(BlockRecord): add new fields

---

book/src/advanced/intersect_options.md
src/sinks/aws_lambda/run.rs
src/sources/common.rs
src/sources/n2c/blocks.rs
src/sources/n2n/run.rs
src/utils/mod.rs

fixed typos

---

src/utils/cursor.rs
src/utils/metrics.rs

This is needed as far as I can tell to be able to use those config structs without deserialization when using Oura as a library.
- For an example of cursor::FileConfig instantiation, see https://github.com/SmaugPool/oura-script-sink/blob/244eac8a2bcd30088537b384ba50c25bba6aec75/src/setup.rs#L39
- For an example of metrics::Config instantiation, see https://github.com/SmaugPool/oura-script-sink/blob/244eac8a2bcd30088537b384ba50c25bba6aec75/src/args.rs#L63
- For an example of metrics::Config cloning, see https://github.com/SmaugPool/oura-script-sink/blob/244eac8a2bcd30088537b384ba50c25bba6aec75/src/setup.rs#L47
Of course adding some constructors is possible too if preferred.

Allow to instanciate cursor::FileConfig and metrics::Config when using Oura as a library

---

src/mapper/map.rs
src/mapper/shelley.rs
src/model.rs
src/sinks/terminal/format.rs

This is used by https://github.com/SmaugPool/oura-script-sink to make all minting policies available on pool.pm.
I'm not sure if we would like to be able to distinguish scripts coming from witnesses from those coming from auxiliary data.
For now this is not the case.

feat: Add native scripts

---

src/mapper/byron.rs
src/mapper/map.rs
src/model.rs

This is especially useful after addition of `PlutusDatum` events.
Not sure how to match datum values to outputs without this.
It's a new field, so likely to break code parsing JSON events -- should I add a note about this somewhere?
Tested with `dump` and `webhook` sinks.

Add `datum_hash` to `TxOutput` events

---

src/sources/common.rs
src/sources/n2c/run.rs
src/sources/n2c/setup.rs
src/sources/n2n/run.rs
src/sources/n2n/setup.rs
src/utils/mod.rs

closes #256
This PR implement a retry mechanism for both N2N / N2C chainsync procedures to handle transient network errors (eg: tcp peer-reset).

feat: Retry whole chainsync operation when possible

---

.editorconfig
.gitignore
flake.lock
flake.nix

So that oura can be built with `nix build` and accessible by other projects using nix, namely [cardano-world](https://github.com/input-output-hk/cardano-world).
cc @blaggacao

Add a nix flake

---

src/mapper/map.rs
src/model.rs
src/sinks/terminal/format.rs

Pool registration metadata needs to be validated against the on chain metadata hash.  This PR will extract the hash as well from the certificate to allow downstream processing and validation of the metadata at that url.

pool registration metadata hash extract

---

book/src/sinks/logs.md
src/sinks/logs/setup.rs

use config field to toggle compression

---

book/src/SUMMARY.md
book/src/sinks/README.md

The Redis Streams sink documentation was missing from the book index.
This fixes that.

docs: Add redis streams documentation to book index

---

src/mapper/babbage.rs
src/mapper/collect.rs
src/mapper/map.rs
src/model.rs

WithdrawalRecord

---

book/src/installation/from_source.md

I noticed a few times people end up wondering why the sink in their config isn't available after building from source.
Usually I tell them to use this flag and their problem goes away.
I added the flag to the install command to avoid this confusion in the future.

chore: add all features flag in from source docs

---

book/src/filters/selection.md

This matches the adjusted method names in selections.rs up for the two misnamed metadata-based predicates

Fixed documentation mismatch for key-based predicates

---

src/sources/n2c/run.rs

Fixed the typo in the error message logged in N2C. 
Fixes https://github.com/txpipe/oura/issues/401

Logging: N2N error logged in N2C #401

---

book/src/usage/watch.md

- Since a recent commit (67b01e8739ed2927ced270e08daea74b03bcc7f7) preview and preprod magic values are also supported.
- Updated the watch.md file according to this.

Updated watch.md - Added preview and preprod magic values

---

Dockerfile

- Updated the Oura Dockerfile to be using bullseye (Debian 11), instead of buster (Debian 10).
Fixes: https://github.com/txpipe/oura/issues/519

Dockerfile uses buster debian, which is end of life #519

---

src/utils/mod.rs

Time calculation was broken for preview / preprod since the re-spin. This PR applies correct values.

fix: Fix time calculation for preview / preprod

---

src/mapper/map.rs

Mapper code doesn't include a datum hash when the datum is provided inline. This PR fixes that by computing the hash on the fly.

fix: Compute datum hash for inline values

---

Cargo.lock
Cargo.toml
src/mapper/babbage.rs
src/mapper/collect.rs
src/mapper/map.rs

To define the hash of an inline datum, Oura was re-encoding the value and computing the corresponding hash. The problem with this approach is that little nuances of non-deterministic CBOR encoding was yielding different hashes from the ones found on-chain.
This PR fixes the issue by upgrading upstream Pallas lib which includes a way to access the original CBOR https://github.com/txpipe/pallas/pull/221
By having access to the original CBOR, we compute the hash using the correct data.

fix: Use original cbor to define inline datum hash

---

src/mapper/byron.rs

We were using the wrong bytes to parse Byron addresses, which resulted on an error trying to crawl Byron transactions. This PR fixes the issue by using the correct data field.

fix: Use correct bytes for Byron addresses

---

src/filters/selection.rs

For one of our projects at MLabs, we'd like the ability to filter based off the signers, the policy ids, and the plutus script hashes as a way to help reduce the amount of data we need to sort through. This PR implements that.

Add vkey filtering

---

src/model.rs

Close #709 
As json does not support i128, I believe the best way is to standardize serialization to string.

fix: json deserialization from payload fails with i128 is not supported

---

src/sinks/gcp_pubsub/run.rs
src/sinks/gcp_pubsub/setup.rs

Solves #710. 
Adding the option to set an ordering key when using pubsub. This should help in ensuring sequential/ordered processing on pubsub side

add ordering key for pubsub

---

Cargo.lock
Cargo.toml
src/sinks/gcp_pubsub/run.rs
src/sinks/gcp_pubsub/setup.rs

We usually use pubsub through an emulator running on docker.
Figured there was no way to configure the emulator on pubsub. This pr added supports for it

Configure pubsub emulator

---

Dockerfile

**Problem:**
- Debian 11 (bullseye) is about to be transitioned to LTS support (August 14th, 2024), which is limited compared to the regular support for stable releases.
For further details please see:
- https://www.debian.org/releases/bullseye/
**Solution:**
- Update the OS version used in the Oura Docker container to Debian 12 (bookworm), so we could profit from higher support level and faster security patching process.

Update OS version to Debian 12 (bookworm)

---

src/sinks/mod.rs
src/sources/n2c.rs
src/sources/n2n.rs

This is needed when using Oura as a library.

fix: fully expose source and sink configs

---

src/bin/oura/main.rs
src/bin/oura/run_daemon.rs
src/daemon/mod.rs
src/lib.rs

To make it easier to test `oura daemon` in #823, we found it practical to split
```rust
// src/bin/oura/daemon.rs
pub fn run(args: &Args) -> Result<(), Error>
```
into:
```rust
// src/daemon/mod.rs
pub fn run_daemon(config: ConfigRoot) -> Result<Daemon, Error>
// src/bin/oura/run_daemon.rs
pub fn run(args: &Args) -> Result<(), Error>
```
to be able to start the daemon with having to first write a temporary config file to disk.

Factor out `run_daemon` and move to library
