book/src/guides/cardano_2_kafka.md
Linking to kafka original site
=> Kakfa official site link

src/mapping.rs
=> Handle non-map metadata structure

.github/workflows/validate.yml, book/src/introduction.md, src/bin/oura/watch.rs, src/sources/common.rs, src/sources/n2c/setup.rs, src/sources/n2n/setup.rs
=> feat: Basic Windows support

Cargo.lock, src/mapping.rs
=> chore(deps): Update Pallas to version 0.3.8

.github/CONTRIBUTING.md, README.md
Added a basic contributing guide. Lots of room for improvement, but seems like a good enough starting point.
=> docs: Add contributing guide

src/bin/oura/daemon.rs, src/bin/oura/dump.rs, src/bin/oura/watch.rs, src/mapper/prelude.rs, src/sinks/elastic/run.rs, src/sinks/elastic/setup.rs, src/sinks/kafka/run.rs, src/sinks/kafka/setup.rs, src/sinks/logs/run.rs, src/sinks/logs/setup.rs, src/sinks/stdout/run.rs, src/sinks/stdout/setup.rs, src/sinks/terminal/run.rs, src/sinks/terminal/setup.rs, src/sinks/webhook/run.rs, src/sinks/webhook/setup.rs, src/sources/common.rs, src/sources/n2c/setup.rs, src/sources/n2n/setup.rs, src/utils/cursor.rs, src/utils/facade.rs, src/utils/mod.rs
=> feat: Introduce stateful cursor

Cargo.lock, Cargo.toml, src/mapper/byron.rs, src/mapper/map.rs, src/mapper/prelude.rs, src/mapper/shelley.rs, src/model.rs, src/sinks/terminal/format.rs, src/sources/n2c/blocks.rs, src/sources/n2c/run.rs, src/sources/n2n/run.rs
closes #145 
does this seem like a reasonable solution?
=> Add `era` to `BlockRecord`

Cargo.lock, Cargo.toml, src/bin/oura/daemon.rs
includes and fixes
- https://github.com/txpipe/oura/pull/157
=> build(deps): config-0.12.0 and fixes

Cargo.lock, Cargo.toml, src/bin/oura/daemon.rs, src/model.rs, src/sinks/aws_s3/mod.rs, src/sinks/aws_s3/run.rs, src/sinks/aws_s3/setup.rs, src/sinks/mod.rs
This new sink will take `Block` events and store an S3 object with the full CBOR content in a configurable bucket.
=> feat: Introduce AWS S3 sink

book/src/advanced/intersect_options.md
=> doc: Add [source.finalize] doc and example

src/mapper/cip15.rs
=> fix: Relax CIP15 requirements and log level

book/src/usage/watch.md, src/sources/common.rs, src/utils/mod.rs
=> feat: Add shortcuts for 'preview' and 'pre-prod' networks

book/src/sinks/webhook.md, src/sinks/webhook/setup.rs
=> feat(webhook): Allow self-signed certificates

src/sinks/elastic/run.rs, src/sinks/elastic/setup.rs
=> fix(elastic): Don't panic on ID conflicts

src/utils/mod.rs
=> Logging: Typo in try_from_magic #404

book/src/advanced/mapper_options.md
- Fixed a typo.
- Added the default value for 'include_byron_ebb'.
=> Updated mapper_options.md

book/src/filters/selection.md
- Fixed some typos.
- Implemented some minor improvements.
=> Updated selection.md - minor improvements

src/filters/deno/mod.rs, src/filters/dsl.rs, src/filters/json.rs, src/filters/legacy_v1/mod.rs, src/filters/noop.rs, src/filters/parse_cbor.rs, src/filters/split_block.rs, src/filters/wasm.rs, src/sinks/aws_lambda.rs, src/sinks/aws_sqs.rs, src/sinks/elasticsearch.rs, src/sinks/filerotate.rs, src/sinks/gcp_pubsub.rs, src/sinks/kafka.rs, src/sinks/noop.rs, src/sinks/rabbitmq.rs, src/sinks/redis.rs, src/sinks/stdout.rs, src/sinks/webhook.rs, src/sources/n2c.rs, src/sources/n2n.rs, src/sources/s3.rs
=> chore: changed stages names

src/sinks/redis.rs
Add support for capping the stream size with the `stream_max_length` option.
```toml
[sink]
type = "Redis"
url = "redis://localhost:6379"
stream_name = "my-stream"
stream_max_length = 100
```
This feature gives more granular control over the max number of items present on the stream.
Closes #454
=> Allow capping the Redis stream size

book/src/advanced/retry_policy.md, src/bin/oura/daemon.rs
The improvement was made in the gasket lib and in the next versions it will already be possible to use!
Closes #635
=> feat: improve config serialization of Duration values

book/src/SUMMARY.md, book/src/sinks/README.md, book/src/sinks/aws_sqs.md, book/src/sinks/elastic.md, book/src/sinks/gcp_cloudfunction.md, book/src/sinks/gcp_pubsub.md, book/src/sinks/rabbitmq.md, book/src/sinks/webhook.md, src/sinks/webhook.rs
=> docs: improve sinks documentation

docs/components/clipboardIcon.jsx, docs/components/configuration.jsx
=> docs: reactive config updates.

book/src/sinks/gcp_pubsub.md, src/sinks/gcp_pubsub/run.rs, src/sinks/gcp_pubsub/setup.rs
this change allow us to filter on subscription level by attribute values
=> feat: add attributes field to GCP pubsub

Cargo.lock, Cargo.toml, examples/dolos_source/daemon.toml, examples/mithril/daemon.toml, src/sources/mithril.rs, src/sources/mod.rs
this PR adds support for Cardano Mithril as Oura source
=> feat(source): Mithril as source support

src/mapper/babbage.rs
Plutus v2 witnesses where missing in babbage txs
=> fix: plutus_v2 witnesses missing in babbage txs

src/filters/select/eval/mod.rs, src/filters/select/mod.rs
=> Expose select filter for library mode

src/filters/rollback_buffer.rs
=> fix: adjusted rollback buffer to support reset events
